import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { getActiveProductionId } from "@/lib/active-production";
import { buildAutoBodies, type RiderAutoSource } from "@/app/(app)/booth/rider-data";
import { PrintButton } from "./print-button";

export default async function RiderPrintPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const pid = await getActiveProductionId();
  if (!pid) redirect("/booth");

  // RLS on productions/rider_sections scopes visibility; if the person can't
  // see this production, both queries come back empty and we bounce.
  const { data: prod } = await supabase
    .from("productions")
    .select("title, organizations(name)")
    .eq("id", pid)
    .maybeSingle();
  if (!prod) redirect("/booth");

  const { data: sections } = await supabase
    .from("rider_sections")
    .select("id, sort_order, title, kind, source, body")
    .eq("production_id", pid)
    .order("sort_order");

  const autoBodies = await buildAutoBodies(supabase, pid);
  const monthYear = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });

  return (
    <div className="min-h-screen bg-paper text-ink">
      <div className="max-w-3xl mx-auto px-8 py-10 print:px-0 print:py-0">
        <div className="flex items-start justify-between mb-8 print:mb-6">
          <div>
            <h1 className="text-3xl font-display uppercase tracking-wide text-brick">
              {prod.title}
            </h1>
            <p className="text-body-md text-ash mt-1 uppercase tracking-widest">
              Technical Rider · {monthYear}
            </p>
          </div>
          <PrintButton />
        </div>

        {(sections || []).length === 0 && (
          <p className="text-body-md text-ash">No rider sections yet. Build the rider in Booth → Rider.</p>
        )}

        <div className="space-y-7 print:space-y-5">
          {(sections || []).map((s) => (
            <section key={s.id} className="break-inside-avoid">
              <h2 className="text-body-md font-semibold uppercase tracking-wide text-brick border-b border-bone pb-1 mb-2">
                {s.title}
              </h2>
              <pre className="whitespace-pre-wrap font-sans text-body-sm leading-relaxed text-ink">
                {s.kind === "auto" && s.source
                  ? autoBodies[s.source as RiderAutoSource]
                  : s.body}
              </pre>
            </section>
          ))}
        </div>

        <p className="mt-10 pt-4 border-t border-bone text-body-xs text-muted print:mt-6">
          {prod.title} · Technical Rider · Generated by Calltime
        </p>
      </div>
    </div>
  );
}
